/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cloud_logic_custom": [
        {
            "name": "meetingApi",
            "endpoint": "https://grmhcrfpca.execute-api.us-west-2.amazonaws.com/uat",
            "region": "us-west-2"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://jjjhfsxbuzc2hfbwq4h5h42fpa.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-mepw7h4idrex7mqttojflbywhi",
    "aws_cognito_identity_pool_id": "us-west-2:ae4bb227-6fa0-49f1-aca5-b9c1e9cbe305",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_VUJHknyb1",
    "aws_user_pools_web_client_id": "4v52aiebbnnivvauhedbne1jvl",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "predictions": {
        "convert": {
            "translateText": {
                "region": "us-west-2",
                "proxy": false,
                "defaults": {
                    "sourceLanguage": "en",
                    "targetLanguage": "es"
                }
            },
            "transcription": {
                "region": "us-west-2",
                "proxy": false,
                "defaults": {
                    "language": "en-US"
                }
            },
            "speechGenerator": {
                "region": "us-west-2",
                "proxy": false,
                "defaults": {
                    "VoiceId": "Justin",
                    "LanguageCode": "en-US"
                }
            }
        }
    }
};
export default awsmobile;
